version: 2.1

orbs:
  docker: circleci/docker@1.7.0

workflows:
  version: 2
  docker_deploy:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          context: docker
